import Header from "@/components/Navbar/Header";
import Body from "@/components/Order/Body";
import Head from "next/head";
import React from "react";
import styles from "@/styles/Order/index.module.scss";
import Footer from "@/components/Footer/Footer";

export default function history() {
  return (
    <div>
      <Head>
        <title>Đơn hàng của tôi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://salt.tikicdn.com/media/upload/2018/12/03/0054c1410e38f1b9f3609c244974dd9c.png"
        />
      </Head>
      <Header></Header>
      <div style={{ backgroundColor: "#f5f5fa" }}>
        <div className={styles.wrapper}>
          <Body></Body>
        </div>
      </div>
      <Footer></Footer>
    </div>
  );
}
