import Head from "next/head";
import React from "react";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home/Home.module.scss";
import Header from "@/components/Navbar/Header";
import Body from "@/components/Home/Body";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
const inter = Inter({ subsets: ["latin"] });

const Home: React.FC = () => {
  return (
    <>
      <Head>
        <title>Tiki - Mua hàng online giá tốt, hàng chuẩn, ship nhanh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://salt.tikicdn.com/media/upload/2018/12/03/0054c1410e38f1b9f3609c244974dd9c.png"
        />
      </Head>

      <div className={styles.homePage}>
        <Header></Header>
        <Body></Body>
      </div>
    </>
  );
};

export default Home;
