import Body from "@/components/DealHot/Body";
import Footer from "@/components/Footer/Footer";
import HeaderCart from "@/components/Navbar/HeaderCart";
import Head from "next/head";
import React from "react";

export default function index() {
  return (
    <div style={{ background: "#f5f5fa", minHeight: "100vh" }}>
      <Head>
        <title>Deal Hot | Tiki</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://salt.tikicdn.com/media/upload/2018/12/03/0054c1410e38f1b9f3609c244974dd9c.png"
        />
      </Head>
      <HeaderCart />
      <Body />
      <Footer />
    </div>
  );
}
